### ISSUE TITLE
hidden files not included in tarball

### ISSUE THREAD

**Issue by aviau** [Debian/dh-make-golang#35] opened 2015-12-20 19:11 UTC
Hidden files are not included in the tarball. In my case, they are needed for tests.

**Comment by anthonyfok** [comment] 2015-12-21 10:36
Sorry, what hidden files exactly?  Could you be more specific, or better yet, give an actual example?  Thanks!

**Comment by aviau** [comment] 2015-12-21 17:49
Files with names starting with a dot(```.```).

A good example is [atlas-go](https://github.com/hashicorp/atlas-go). The folder ```atlas-go/archive/test-fixtures/archive-hg/.hg``` was not included in the tarball.

**Comment by anthonyfok** [comment] 2015-12-21 19:28
It is not hidden files that are excluded, as files like `.goxc.json`, `.mailmap` and `.travis.yml` are certainly included in the tarballs.

A quick look at the dh-make-golang source code in `make.go` reveals that the tarball is created with tar’s `--exclude-vcs` option, which “exclude version control system directories” like `.hg`.  See https://www.gnu.org/software/tar/manual/html_section/tar_49.html for the list of files that are excluded with this option.

**Comment by stapelberg** [comment] 2015-12-25 16:25
As @anthonyfok clarified, it’s intentional that revision control system directories are excluded.

Including such files or directories will result in Lintian warnings, see https://lintian.debian.org/tags/package-contains-vcs-control-dir.html

I’ll close this issue as everything is working as intended. If you think something should be done, please re-open and clarify.

**Closed by stapelberg** 2015-12-25 16:25 UTC
